### ISSUE TITLE
Version Bump

### ISSUE THREAD

**Issue by duckman** [zokradonh/ecogameserver#1]
Looks like there is a script that's supposed to be keeping this updated, but it seems to be behind now? Latest as of right now is 8.1.3-beta but the image is installing 8.0.7-beta

**Comment by zokradonh** [comment]
Background script is up and running with restart:always policy.

I do not play ECO anymore. If there are any issues you can let me know or propose a fix.

**Comment by zokradonh** [comment]
What I didn't mention: It was not running before, but I fixed it.

Looks good now, closing this. Please open a new issue if you still have problems or reopen if this is possible.
